services:
  discord-yt-bot:
    image: ghcr.io/dongdevcom/discord-yt-bot:latest
    container_name: discord-yt-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./.env:/app/.env
      - ./cookie.txt:/app/cookie.txt
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: on-failure
